FROM ubuntu:18.04

RUN apt-get update
RUN apt-get -y install git build-essential vim
RUN apt-get -y install lv2-dev libfftw3-dev liblscp-dev libqt5x11extras5-dev libmad0-dev libsamplerate0-dev librubberband-dev lvtk-dev liblilv-dev libsuil-dev pyqt5-dev-tools qt5-qmake qt5-default libsndfile1-dev liblo-dev libjack-jackd2-dev libasound2-dev libgig-dev libfluidsynth-dev ladspa-sdk dssi-dev
